
server:
  port: 8080
#  servlet:
#    context-path: /system
logging:
  level:
    root: info
    druid:
      sql:
        Statement: info
spring:
  profiles:
    active: dev
  application:
    name: gateway
  devtools:
    add-properties: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: on
          lower-case-service-id: true
          filters:
            - name: RewritePath
              args:
                regexp: "'/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/' + serviceId +'/${remaining}'"

    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
        #instance-id:
        #health-check-path:
        health-check-interval: 30s
        health-check-timeout: 5s
        health-check-critical-timeout: 1s
        heartbeat:
          enabled: true
          ttl-unit: s
          ttl-value: 2
debug: true