server:
  port: 8092
  #servlet:
    #context-path: /system
logging:
  level:
    root: info
    druid:
      sql:
        Statement: info
spring:
  profiles:
    active: dev
  application:
    name: admin
  devtools:
    add-properties: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        service-name: ${spring.application.name}
        #instance-id:
        #health-check-path:
        health-check-interval: 30s
        health-check-timeout: 5s
        health-check-critical-timeout: 1s
        heartbeat:
          enabled: true
          ttl-unit: s
          ttl-value: 2
        instance-id: ${spring.application.name}:${server.port}
